config/routes.rb
Rails.application.routes.draw do

  get '/home' => 'frontpages#index'

  get '/about' => 'frontpages#about'

  resources :custodies
  resources :breeds
  resources :dogs
  resources :owners
  root 'frontpages#index'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :breed
  has_many :custodies
  has_many :owners, :through => :custodies

validates :name, :breed_id, :owner_id, :dob, presence: true

def last_comma_first
    "#{last_name}, #{first_name}"
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    if params[:search]
      @dogs = Dog.where("name LIKE ?", "%#{params[:search]}%")

      if @dogs.size.zero?
        flash[:alert] = "Sorry, no result found."
        @dogs = Dog.all
      end
    elsif params[:breed_id]
      @dogs = Dog.where(breed_id: params[:breed_id])

    else
      @dogs = Dog.all
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new

  end

  # GET /dogs/1/edit
  def edit

  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

respond_to do |format|

        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }

    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.fetch(:dog, {})
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for(@dog) do |f| %>
   <% if @dog.errors.any? %>

<div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this owner from being saved:</h2>

       <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<h1>Listing Dogs</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>DOB</th>
      <th>Breed</th>
      <th>Medical Condition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.dob %></td>
        <td><%= dog.breed.name %></td>
        <td><%= dog.medical_condition %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
  <%= link_to "Add a new dog", new_dog_path, class: "btn btn-primary" %>
</p>

app/views/dogs/new.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">

<h1>New Dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>First name:</strong>
  <%= @owner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @owner.last_name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @dog.dob %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @dog.breed.name %>
</p>

<p>
  <strong>Medical Condition:</strong>
  <%= @dog.medical.condition %>
</p>


<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dog_path %>