config/routes.rb
Rails.application.routes.draw do

  get '/home' => 'frontpages#index'

  get '/about' => 'frontpages#about'

  resources :custodies
  resources :breeds
  resources :dogs
  resources :owners
  root 'frontpages#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :dogs

  validates :breed_name, presence: true

end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  before_action :set_breed, only: [:show, :edit, :update, :destroy]

  # GET /breeds
  # GET /breeds.json
  def index
    @breeds = Breed.all
  end

  # GET /breeds/1
  # GET /breeds/1.json
  def show
  end

  # GET /breeds/new
  def new
    @breed = Breed.new
  end

  # GET /breeds/1/edit
  def edit
  end

  # POST /breeds
  # POST /breeds.json
  def create
    @breed = Breed.new(breed_params)

    respond_to do |format|
      if @breed.save
        format.html { redirect_to @breed, notice: 'Breed was successfully created.' }
        format.json { render :show, status: :created, location: @breed }
      else
        format.html { render :new }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breeds/1
  # PATCH/PUT /breeds/1.json
  def update
    respond_to do |format|
      if @breed.update(breed_params)
        format.html { redirect_to @breed, notice: 'Breed was successfully updated.' }
        format.json { render :show, status: :ok, location: @breed }
      else
        format.html { render :edit }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1
  # DELETE /breeds/1.json
  def destroy
    @breed.destroy
    respond_to do |format|
      format.html { redirect_to breeds_url, notice: 'Breed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breed
      @breed = Breed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def breed_params
      params.fetch(:breed, {})
    end
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/views/breeds/_form.html.erb
<%= form_for(@breed) do |f| %>
  <% if @breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
      <% @breed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breeds/edit.html.erb
<h1>Editing Breed</h1>

<%= render 'form' %>

<%= link_to 'Show', @breed %> |
<%= link_to 'Back', breeds_path %>

app/views/breeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breeds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breeds.each do |breed| %>
      <tr>
        <td><%= link_to 'Show', breed %></td>
        <td><%= link_to 'Edit', edit_breed_path(breed) %></td>
        <td><%= link_to 'Destroy', breed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breed', new_breed_path %>

app/views/breeds/new.html.erb
<h1>New Breed</h1>

<%= render 'form' %>

<%= link_to 'Back', breeds_path %>

app/views/breeds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_breed_path(@breed) %> |
<%= link_to 'Back', breeds_path %>