config/routes.rb
Rails.application.routes.draw do

  get '/home' => 'frontpages#index'

  get '/about' => 'frontpages#about'

  resources :custodies
  resources :breeds
  resources :dogs
  resources :owners
  root 'frontpages#index'

end

app/models/custody.rb
class Custody < ActiveRecord::Base
  belongs_to :owner
  belongs_to :dog

end

app/controllers/custodies_controller.rb
class CustodiesController < ApplicationController
  before_action :set_custody, only: [:show, :edit, :update, :destroy]

  # GET /custodies
  # GET /custodies.json
  def index
    @custodies = Custody.all
  end

  # GET /custodies/1
  # GET /custodies/1.json
  def show
  end

  # GET /custodies/new
  def new
    @custody = Custody.new

  end

  # GET /custodies/1/edit
  def edit
  end

  # POST /custodies
  # POST /custodies.json
  def create
    @custody = Custody.new(custody_params)

    respond_to do |format|
      if @custody.save
        format.html { redirect_to @custody, notice: 'Custody was successfully created.' }
        format.json { render :show, status: :created, location: @custody }
      else
        format.html { render :new }
        format.json { render json: @custody.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custodies/1
  # PATCH/PUT /custodies/1.json
  def update
    respond_to do |format|
      if @custody.update(custody_params)
        format.html { redirect_to @custody, notice: 'Custody was successfully updated.' }
        format.json { render :show, status: :ok, location: @custody }
      else
        format.html { render :edit }
        format.json { render json: @custody.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custodies/1
  # DELETE /custodies/1.json
  def destroy
    @custody.destroy
    respond_to do |format|
      format.html { redirect_to custodies_url, notice: 'Custody was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custody
      @custody = Custody.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custody_params
      params.fetch(:custody, {})
    end
end

app/helpers/custodies_helper.rb
module CustodiesHelper
end

app/views/custodies/_form.html.erb
<%= simple_form_for(@custody) do |f| %>
  <% f.error_notification %>

    <div class="form-inputs">
      <%= f.input :first_name %>
      <%= f.input :last_name %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
    <% end %>

app/views/custodies/edit.html.erb
<h1>Editing Custody</h1>

<%= render 'form' %>

<%= link_to 'Show', @custody %> |
<%= link_to 'Back', custodies_path %>

app/views/custodies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Custodies</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @custodies.each do |custody| %>
      <tr>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= link_to 'Show', custody %></td>
        <td><%= link_to 'Edit', edit_custody_path(custody) %></td>
        <td><%= link_to 'Destroy', custody, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
  <%= link_to 'New Custody', new_custody_path, class: "btn btn-default" %>
</p>

app/views/custodies/new.html.erb
<h1>New Custody</h1>

<%= render 'form' %>

<%= link_to 'Back', custodies_path %>

app/views/custodies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_custody_path(@custody) %> |
<%= link_to 'Back', custodies_path %>